export const commune = [
  {
    name: "Cerrillos",
    code: "CRL",
  },
  {
    name: "Cerro Navia",
    code: "CRN",
  },
  {
    name: "Conchalí",
    code: "VEN",
  },
  {
    name: "El bosque",
    code: "GTM",
  },
  {
    name: "Estacion Central",
    code: "MEX",
  },
  {
    name: "Huechuraba",
    code: "BLZ",
  },
  { name: "El Bosque", code: "EBQ" },
  { name: "Estación Central", code: "ECT" },
  { name: "Huechuraba", code: "HUE" },
  { name: "Independencia", code: "INDP" },
  { name: "La Cisterna", code: "CIS" },
  { name: "La Florida", code: "FLO" },
  { name: "La Granja", code: "GRA" },
  { name: "La Pintana", code: "PNT" },
  { name: "La Reina", code: "REI" },
  { name: "Las Condes", code: "CON" },
  { name: "Lo Barnechea", code: "BAR" },
  { name: "Lo Espejo", code: "ESP" },
  { name: "Lo Prado", code: "PRA" },
  { name: "Macul", code: "MCL" },
  { name: "Maipú", code: "MIP" },
  { name: "Ñuñoa", code: "NUO" },
  { name: "Padre Hurtado", code: "PHU" },
  { name: "Pedro Aguirre Cerda", code: "PAC" },
  { name: "Peñalolén", code: "PEN" },
  { name: "Pirque", code: "PIR" },
  { name: "Providencia", code: "PRO" },
  { name: "Pudahuel", code: "PUD" },
  { name: "Puente Alto", code: "PAL" },
];
